[package]
name = "lila-openingexplorer-import"
publish = false
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
pgn-reader = "0.26"
btoi = "0.4"
reqwest = { version = "0.12", features = ["blocking", "json"] }
bzip2 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_with = "3"
serde_json = "1"
clap = { version = "4", features = ["derive", "deprecated"] }
crossbeam = "0.8"
indicatif = "0.17"
zstd = "0.13"
time = "0.3"
