name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha
          outputs: type=local,dest=dist
      - uses: actions/upload-artifact@v4
        with:
          name: lila-openingexplorer
          path: dist/usr/local/bin/lila-openingexplorer
      - uses: actions/upload-artifact@v4
        with:
          name: import-lichess
          path: dist/usr/local/bin/import-lichess
